rtx.antiCulling.object.enable = True
rtx.lightConversionDistantLightFixedAngle = 0.0349
rtx.worldSpaceUiBackgroundTextures = -0x196FBE2CAB23CB16, -0x3AE04A318AA2ABB1, -0x645CF1DD53FF6357, -0x6AC1CFA187D094AA, -0xAEFF15798CCD7C0E
rtx.worldSpaceUiTextures = -0x196FBE2CAB23CB16, -0x4E866A84552FD39A, -0x645CF1DD53FF6357, -0x6AC1CFA187D094AA, -0xA7CBBE4B23C16C44, -0xF1A42F0E82DC4604
rtx.ignoreLastTextureStage = False
rtx.geometryAssetHashRuleString = indices,texcoords,geometrydescriptor
rtx.allowCubemaps = False
rtx.graph.enable = True
rtx.enableLegacyRectLightConeShaping = False
rtx.antiCulling.light.enable = True
rtx.useVertexCapture = False
rtx.neuralRadianceCache.resetSceneBoundsOnCameraCut = False
rtx.particleTextures = -0x0AB9F87BFA6F8D28, -0x196FBE2CAB23CB16, -0x735E25575F1EAC7C, -0xA808F9F82BE29ABC, -0xD0E0D57A3AB84F1D, -0xEA0A8CC4E7F589A7
rtx.captureHotKey = CTRL,SHFT,P
rtx.captureInstances = True
rtx.fallbackLightMode = 0
rtx.enableDirectLighting = True
rtx.opacityMicromap.showAdvancedOptions = False
rtx.enableProbabilisticUnorderedResolveInIndirectRays = True
rtx.vertexColorIsBakedLighting = True
rtx.ignoreGameDirectionalLights = False
rtx.camera.freeCameraPosition = 0, 0, 0
rtx.freeCameraSpeed = 15.7
rtx.bloom.enable = False
rtx.camera.freeCameraPitch = 0
rtx.playerModel.enablePrimaryShadows = True
rtx.debugView.composite.compositeViewIdx = 0
rtx.particles.enable = True
rtx.fallbackLightType = 0
rtx.defaultToAdvancedUI = True
rtx.camera.freeCameraYaw = 0
rtx.autoExposure.evMinValue = -80
rtx.lightConversionDistantLightFixedIntensity = 2.21
rtx.captureOverwriteExistingCapture = False
rtx.leftHandedCoordinateSystem = False
rtx.ignoreGameSpotLights = False
rtx.enableCullingInSecondaryRays = False
rtx.opacityMicromap.building.splitBillboardGeometry = True
rtx.opacityMicromap.enableBinding = True
rtx.autoExposure.enabled = True
rtx.enableShaderExecutionReorderingInPathtracerIntegrateIndirect = True
rtx.debugView.debugViewIdx = 0
rtx.skyBoxTextures = 0x4822C3D374F8E5ED, 0xA23FA925AC35598D, 0xFBC6C5FFCC8AD259, -0x18B606E2E3F7E0DC, -0x645CF1DD53FF6357
rtx.enableSecondaryBounces = True
rtx.enableCulling = True
rtx.fallbackLightDirection = -0.2, -1, 0.4
rtx.enableRectLightConeShapingRatioScaling = False
rtx.camera.lockFreeCamera = False
rtx.orthographicIsUI = True
rtx.capture.correctBakedTransforms = False
rtx.autoExposure.evMaxValue = 13.01
rtx.enableAlwaysCalculateAABB = True
rtx.captureShowMenuOnHotkey = False
rtx.useVertexCapturedNormals = True
rtx.zUp = False
rtx.suppressLightKeeping = False
rtx.useBuffersDirectly = False
rtx.ignoreLights = -0x645CF1DD53FF6357
rtx.viewModel.enable = False
rtx.opacityMicromap.enableResetEveryFrame = False
rtx.ignoreGamePointLights = False
rtx.useHighlightLegacyMode = False
rtx.raytracedRenderTarget.enable = True
rtx.camera.enableFreeCamera = False
rtx.lightConversionSphereLightFixedRadius = 0.18
rtx.fallbackLightRadiance = 100, 100, 100
rtx.lightConversionMaxIntensity = 1e+06
rtx.skyAutoDetect = 0
rtx.opacityMicromap.enable = True
rtx.useHighlightUnsafeAnchorMode = False
rtx.enableRussianRoulette = True
rtx.enableRaytracing = True
rtx.fogIgnoreSky = False
rtx.useWorldMatricesForShaders = True
rtx.localtonemap.finalizeWithACES = True
rtx.fallbackLightAngle = 5
rtx.enableMultiStageTextureFactorBlending = True
